# Display
name: GCore
author: GuillaumeVDN
description: 'Core for GuillaumeVDN''s plugins'
website: www.guillaumevdn.com
# Techy
version: 7.0.0
api-version: 1.13
main: be.guillaumevdn.gcore.GCore
softdepend: [Vault,PlaceholderAPI,Multiverse-Core,ProtocolLib]
# Commands
commands:
  gcore:
    description: 'GCore plugins command'
# Permission
permissions:
  gcore.admin:
    default: op
  gcore.reload:
    default: op
