# Display
name: PyrCore
author: GuillaumeVDN
description: 'Core for GuillaumeVDN''s plugins'
website: www.guillaumevdn.com
# Techy
version: 7.0.0
api-version: 1.13
main: be.pyrrh4.pyrcore.PyrCore
softdepend: [Vault,PlaceholderAPI,Multiverse-Core,ProtocolLib]
# Commands
commands:
  pyrcore:
    aliases: [pyr]
    description: 'PyrCore plugins command'
# Permission
permissions:
  pyr.core.admin:
    default: op
  pyr.core.reload:
    default: op
