# display
name: GCore
description: Core library for GuillaumeVDN's plugins
author: GuillaumeVDN
website: www.guillaumevdn.com
# techy
version: 8.43.0
api-version: 1.13
main: com.guillaumevdn.gcore.GCore
softdepend:
  - Vault
  - ProtocolLib
  - Citizens
  - DeluxeChat
  - MythicMobs
  - PlaceholderAPI
  - PlayerPoints
  - TokenEnchant
  - HeadDatabase
loadbefore:
  - GCoreLegacy
  - QuestCreator
# commands
commands:
  gcore:
    aliases: [gcore]
    description: 'Main command for GCore'
# permissions
permissions:
  # (super)
  gcore.*:
    default: op
    children:
      # gcore.admin (mainly allow usage of admin commands)
      gcore.admin:
        default: op
      # gcore.bypass_command_restrictions (allow bypassing of commands restriction elements)
      gcore.bypass_command_restrictions:
        default: op
